# Site
name: "State of Heavy"
title: "State of Heavy"
description: "Gravitas Musica"
logo: 'assets/images/state-of-heavy-logos.jpeg'
favicon: 'assets/images/cthulhu.png'
url: 'https://www.stateofheavy.com'
baseurl: ''
google_analytics: 'G-EHJ1HB6KSQ'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: email@stateofheavy.com

# Authors
authors:
  mark:
    name: Mark
    display_name: Mark
    gravatar: f8677d00f7921e9f9d99fdd4887e6122
    email: editor@stateofheavy.com
    web: https://www.stateofheavy.com
    #twitter: https://twitter.com/wowthemesnet
    description: "Editor in Chief of StateOfHeavy.com - fat bastard."
  chris:
    name: Chris
    display_name: Chris
    gravatar: f8677d00f7921e9f9d99fdd4887e6122
    email: chris@stateofheavy.com
    web: https://www.stateofheavy.com
    #twitter: https://twitter.com/wowthemesnet
    description: "Contributing Editor to StateOfHeavy.com - cool bastard."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 9
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
